### PR TITLE
use correct @args

### PR DESCRIPTION
**Pull request by scmorrison**

### CODE REVIEW

**Comment by scmorrison** [comment]
This should also resolve #148.

**Comment by ufobat** [comment]
I am not yet perfectly sure, but my first impression is that the last of the 2 commits fixes the issue at the wrong position.

**Comment by scmorrison** [comment]
Yeah, same here. This solved the immediate issue I was looking into, but I am not sure where you are heading with this @*ARGS usage. I am wondering if @*ARGS usage should be moved to `bin/bailador` instead of inside the libs and then just passed to the appropriate sub when args are passed to the `bailador` command.

https://github.com/Bailador/Bailador/blob/dev/lib/Bailador/App.pm#L86

**Comment by ufobat** [comment]
i think you're right! if i understood you correctly the $*ARGS should not be included in baile() at all.

when you parse them in bin/bailador and "convert" them into parameters for $*ENV<BAILADOR> wouldnt that be better?

**Comment by scmorrison** [comment]
Yeah, I think that makes the most sense. Also, I have rolled back that second commit as well.

**Comment by ufobat** [comment]
okay! will you put this into bin/bailador? :-)

**Comment by scmorrison** [comment]
Thanks, Sure, I will take a look this week.

**Pull request merged**
