### PR TITLE
conventional imports

### PR DESCRIPTION
**Pull request by Emeric54**
A _small_ PR, to propose a convention about imports, inspired by Django projects. Clean imports should be : 
```perl6
use v6.c;

## External modules, sorted alphabetically
use HTTP::Easy::PSGI;
use Log::Any;
...

## Related modules to Bailador, sorted alphabetically
use Bailador::Configuration;
use Bailador::Sessions;
...
```
Just my 2 cents. 💲

### CODE REVIEW

**Comment by ufobat** [comment]
Good idea, we do the same at work as well.
maybe we could somehow include this in the t/00-* test series?

**Comment by Emeric54** [comment]
done !

**Comment by szabgab** [comment]
👍 and yes, please also send a pr for t/00-lint.t to enforce this.

**Comment by szabgab** [comment]
Oh you did it already. Nice!

**Pull request merged**
